# Generated by Django 3.0.5 on 2020-04-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('-created_at', '-pk')},
        ),
    ]
